/** Solved examples for topic virknes — full text from PDF (seed via updateSolvedExamples). */
export default [
  {
    id: 'ex1',
    problem:
      'Dota skaitļu virkne $1; 1; 2; 5; 9; 6; \\ldots$. Tā tiek veidota pēc likuma: virknes pirmie divi locekļi ir $1$, bet katrs nākamais ir vienāds ar divu iepriekšējo virknes locekļu kvadrātu summas pēdējo ciparu.\n\na) Noteikt, vai šīs virknes $2026.$ loceklis ir pāra vai nepāra skaitlis!\n\nb) Aprēķināt virknes $2026.$ locekli!',
    solution:
      '**a)** Pāra skaitļus virknē apzīmējam ar $p$, nepāra — ar $n$. Ja diviem iepriekšējiem virknes locekļiem ir vienāda paritāte (abi ir pāra skaitļi vai abi ir nepāra skaitļi), tad nākamais virknes loceklis būs pāra skaitlis, savukārt, ja diviem iepriekšējiem virknes locekļiem ir atšķirīgas paritātes, tad nākamais virknes loceklis būs nepāra skaitlis. Līdz ar to iegūstam virkni $n; n; p; n; n; p; n; \\ldots$ Redzams, ka šī virkne ir periodiska ar perioda garumu $3$. Tāpēc tikai tie virknes locekļi, kuru kārtas numurs dalās ar $3$, ir pāra. Tā kā $2026$ ar $3$ nedalās, tad $2026.$ loceklis ir nepāra.\n\n**b)** Turpinot virkni tālāk, iegūsim, ka tā ir $1; 1; 2; 5; 9; 6; 7; 5; 4; 1; 7; 0; 9; 1; 2; 5; \\ldots$ Tā kā katrs nākamais virknes loceklis ir atkarīgs no diviem iepriekšējiem virknes locekļiem, tad, līdzko parādās divi jau iepriekš bijuši skaitļi, izveidojas periods. Tā kā virknes otrais un trešais loceklis ir $1$ un $2$, un $14.$ un $15.$ loceklis arī ir $1$ un $2$, tad virkne, sākot ar $2.$ locekli, ir periodiska ar perioda garumu $12$. Tāpēc pēdējais pilnais periods pirms $2026.$ virknes locekļa beidzas pie $2017.$ virknes locekļa, jo $1 + 12 \\cdot 168 = 2017$. Tā kā $2026 - 2017 = 9$, tad $2026.$ loceklis ir periodā devītais, tātad tas ir $\\mathbf{1}$.\n\n**Piezīme.** Pietiek atrisināt tikai b) gadījumu un no tā secināt par skaitļa paritāti, tas ir, sniegt atbildi a) gadījumam.',
  },
  {
    id: 'ex2',
    problem:
      'Virknes pirmais loceklis ir $6$ ($a_1 = 6$). Katru nākamo locekli aprēķina pēc formulas:\n$$a_{n+1} = \\begin{cases} \\dfrac{a_n}{2}, & \\text{ja } a_n \\text{ — pāra} \\\\ 5a_n - 1, & \\text{ja } a_n \\text{ — nepāra} \\end{cases}$$\nKāds virknes locekļa kārtas numurs ir vienāds ar šajā vietā esošo virknes locekli, tas ir, kādiem $n$ izpildās $a_n = n$?',
    solution:
      'Pamatosim, ka $13.$ un $16.$ virknes loceklis sakrīt ar tā kārtas numuru virknē. Turpinot virkni tālāk, iegūsim:\n$$6,\\ 3,\\ 14,\\ 7,\\ 34,\\ 17,\\ 84,\\ 42,\\ 21,\\ 104,\\ 52,\\ 26,\\ 13,\\ 64,\\ 32,\\ 16,\\ 8,\\ 4,\\ 2,\\ 1,\\ 4,\\ 2,\\ 1,\\ \\ldots$$\n$$1.\\ \\ 2.\\ \\ 3.\\ \\ 4.\\ \\ 5.\\ \\ 6.\\ \\ 7.\\ \\ 8.\\ \\ 9.\\ \\ 10.\\ \\ 11.\\ \\ 12.\\ \\ 13.\\ \\ 14.\\ \\ 15.\\ \\ 16.\\ \\ 17.\\ \\ 18.\\ \\ 19.\\ \\ 20.\\ \\ 21.\\ \\ 22.\\ \\ 23.$$\nTā kā katrs nākamais virknes loceklis ir atkarīgs tikai no viena iepriekšējā, tad, līdzko parādās kāds šajā virknē jau iepriekš bijis skaitlis, izveidojas periods. Kā redzams, sākot ar $18.$ virknes locekli, virknē atkārtojas skaitļu grupa $(4; 2; 1)$, tāpēc tālāk uz priekšu neviens virknes locekļa kārtas numurs nebūs vienāds ar pašu virknes locekli. Līdz ar to vienīgie virknes locekļi, kam prasītais izpildās, ir $13$ un $16$.',
  },
  {
    id: 'ex3',
    problem:
      'Naturālu skaitļu virknes $1; 8; 8; 64; 192; 432; \\ldots$ katrs loceklis, sākot ar trešo, ir vienāds ar divu iepriekšējo locekļu nenulles ciparu reizinājumu. Kāds ir šīs virknes $2025.$ loceklis?',
    solution:
      'Turpinot virkni tālāk, iegūsim, ka tā ir (ar pelēkiem cipariem norādīts katra virknes locekļa nenulles ciparu reizinājums):\n$$1;\\ 8;\\ 8;\\ 64;\\ 192;\\ 432;\\ 432;\\ 576;\\ 5040;\\ 4200;\\ 160;\\ 48;\\ 192;\\ 576;\\ 3780;\\ 35280;\\ 40320;\\ 5760;\\ 5040;\\ 4200;\\ \\ldots$$\n$$1\\ \\ \\ 8\\ \\ \\ 8\\ \\ \\ 24\\ \\ 18\\ \\ 24\\ \\ 24\\ \\ 210\\ \\ 20\\ \\ 8\\ \\ \\ 6\\ \\ \\ 32\\ \\ 18\\ \\ 210\\ 168\\ 240\\ \\ 24\\ \\ 210\\ \\ 20\\ \\ \\ 8$$\nTā kā katrs nākamais virknes loceklis ir atkarīgs no diviem iepriekšējiem virknes locekļiem, tad, līdzko parādās divi jau iepriekš bijuši skaitļi, izveidojas periods. Tā kā virknes devītais un desmitais loceklis ir $5040$ un $4200$, un $19.$ un $20.$ loceklis arī ir $5040$ un $4200$, tad virkne, sākot ar $9.$ locekli, ir periodiska un perioda garums ir $10$. Tāpēc pēdējais pilnais periods beidzas pie $2018.$ virknes locekļa un $2025.$ loceklis ir nākamā perioda $7.$ loceklis, jo $2025 = 8 + 10 \\cdot 201 + 7$, un tātad $2025.$ loceklis ir $\\mathbf{3780}$.',
  },
  {
    id: 'ex4',
    problem:
      'Cik dažādos veidos kā divnieku un trijnieku summu var izteikt skaitli a) $14$; b) $22$? Veidi, kas atšķiras ar saskaitāmo secību, ir uzskatāmi par dažādiem. Piemēram, skaitli $8$ var izteikt četros dažādos veidos:\n$$8 = 2+2+2+2 = 2+3+3 = 3+2+3 = 3+3+2.$$',
    solution:
      'Ar $a_n$ apzīmējam, cik dažādos veidos skaitli $n$ var izteikt kā divnieku un trijnieku summu. Iegūstam tabulu:\n\n| $n$ | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|---|---|---|---|---|---|---|---|---|---|\n| $a_n$ | 1 | 1 | 1 | 2 | 2 | 3 | 4 | 5 | 7 |\n\nPamatosim, ka šīs tabulas apakšējā rindā katrs skaitlis, sākot ar ceturto, ir to divu skaitļu summa, kas atrodas divas un trīs pozīcijas pirms tā, tas ir, to var uzrakstīt ar rekurences formulu $a_n = a_{n-3} + a_{n-2}$, kur $n \\geq 5$.\n\nSkaitli $n$ var uzrakstīt kā divnieku un trijnieku summu $a_n$ dažādos veidos. Iespējami divi dažādi gadījumi:\n- Ja pēdējais saskaitāmais ir $3$, tad katrai summai pārējo saskaitāmo summa (bez pēdējā trijnieka) ir $(n - 3)$, un šādu summu skaits ir $a_{n-3}$.\n- Ja pēdējais saskaitāmais ir $2$, tad katrai summai pārējo saskaitāmo summa (bez pēdējā divnieka) ir $(n - 2)$, un šādu summu skaits ir $a_{n-2}$.\n\nTā kā katra summa atšķiras no katras citas summas ar pēdējo saskaitāmo, tad formula $a_n = a_{n-3} + a_{n-2}$ ir patiesa. Tagad, izmantojot iegūto rekurences formulu, aizpildām tabulu:\n\n| $n$ | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| $a_n$ | 1 | 1 | 1 | 2 | 2 | 3 | 4 | 5 | 7 | 9 | 12 | 16 | 21 | 28 | 37 | 49 | 65 | 86 | 114 | 151 | 200 |\n\nTātad a) skaitli $14$ kā divnieku un trijnieku summu var izteikt $\\mathbf{21}$ veidā; b) skaitli $22$ kā divnieku un trijnieku summu var izteikt $\\mathbf{200}$ veidos.',
  },
  {
    id: 'ex5',
    problem:
      'No mājām līdz ieejai dzīvoklī ir $12$ pakāpieni. Ar vienu soli var pārkāpt $1$, $2$ vai $3$ pakāpienus. Cik dažādos veidos var uzkāpt līdz dzīvoklim no ieejas? (Veidus uzskata par atšķirīgiem, ja atšķiras izdarīto soļu secība, piemēram, kāpt $2; 3; 1$ pakāpienus un kāpt $1; 2; 3$ pakāpienus ir divi atšķirīgi veidi.)',
    solution:
      'Ar $a_n$ apzīmējam, cik dažādos veidos var nokļūt uz $n$-tā pakāpiena. Sadalīsim visus šos veidus $3$ grupās atkarībā no pēdējā soļa, ar kuru nonāk uz $n$-tā pakāpiena:\n- uz $n$-tā pakāpiena ar vienu soli var nokļūt no $(n-1)$-ā pakāpiena, uz kura var nokļūt $a_{n-1}$ veidos;\n- uz $n$-tā pakāpiena ar vienu soli var nokļūt no $(n-2)$-ā pakāpiena, uz kura var nokļūt $a_{n-2}$ veidos;\n- uz $n$-tā pakāpiena ar vienu soli var nokļūt no $(n-3)$-ā pakāpiena, uz kura var nokļūt $a_{n-3}$ veidos.\n\nCitu variantu, kā ar vienu soli nokļūt uz $n$-tā pakāpiena, nav. Tātad uz $n$-tā pakāpiena pavisam var nokļūt $a_n = a_{n-1} + a_{n-2} + a_{n-3}$ atšķirīgos veidos. Izmantojot šo sakarību un sākuma vērtības $a_1 = 1$ un $a_2 = 2$, aprēķinām $a_{12}$.\n\n| $n$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| $a_n$ | 1 | 2 | 4 | 7 | 13 | 24 | 44 | 81 | 149 | 274 | 504 | 927 |\n\nLīdz ar to atšķirīgos veidos var kāpt $\\mathbf{927}$ veidos.',
  },
  {
    id: 'ex6',
    problem:
      'Cik dažādos veidos taisnstūri $2 \\times 12$ var sagriezt taisnstūros $1 \\times 2$? (Griezumi, kas iegūstami viens no otra ar simetriju vai pagriezienu, tiek uzskatīti par dažādiem.)',
    solution:
      'Mēģināsim pakāpeniski noskaidrot, cik dažādos veidos var sagriezt taisnstūri $2 \\times 2$, $2 \\times 3$, $2 \\times 4$ un $2 \\times 5$. Sāksim taisnstūra griešanu no kreisās malas.\n\nTaisnstūri $2 \\times 2$ var sagriezt $2$ dažādos veidos — griežot vertikāli vai horizontāli.\n\nTaisnstūri $2 \\times 3$ var sagriezt $3 = 2 + 1$ dažādos veidos — pirmo griezienu var izdarīt vertikāli, tad iegūstam $2$ dažādus veidus, vai horizontāli, tad iegūstam $1$ veidu.\n\nTaisnstūri $2 \\times 4$ var sagriezt $5 = 3 + 2$ dažādos veidos — pirmo griezienu var izdarīt vertikāli, tad iegūstam $3$ dažādus veidus, vai horizontāli, tad iegūstam $2$ dažādus veidus.\n\nTaisnstūri $2 \\times 5$ var sagriezt $8 = 5 + 3$ dažādos veidos — pirmo griezienu var izdarīt vertikāli, tad iegūstam $5$ dažādus veidus, vai horizontāli, tad iegūstam $3$ dažādus veidus.\n\nIevērojam:\n- ja pirmo griezienu izdara vertikāli, tad vēl jāsagriež taisnstūris, kura garums ir par $1$ mazāks nekā dotajam taisnstūrim;\n- ja pirmo griezienu izdara horizontāli, tad noteikti arī jānogriež otrs horizontālais taisnstūris $1 \\times 2$, līdz ar to vēl jāsagriež taisnstūris, kura garums ir par $2$ mazāks nekā dotajam taisnstūrim.\n\nAr $a_n$ apzīmējam dažādo veidu skaitu, kā var sagriezt taisnstūri $2 \\times n$. Iegūstam, ka $a_n = a_{n-1} + a_{n-2}$. Izmantojot šo sakarību un atrastās sākuma vērtības $a_1 = 1$ un $a_2 = 2$, aprēķinām $a_{12}$.\n\n| $n$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |\n|---|---|---|---|---|---|---|---|---|---|---|---|---|\n| $a_n$ | 1 | 2 | 3 | 5 | 8 | 13 | 21 | 34 | 55 | 89 | 144 | 233 |\n\nTātad taisnstūri $2 \\times 12$ var sagriezt $\\mathbf{233}$ dažādos veidos.',
  },
  {
    id: 'ex7',
    problem:
      'Rindā salikti $10$ krēsli, uz katra no tiem sēž pa skolēnam. Skolēniem vienu reizi atļauts piecelties un apsēsties citā secībā, pie tam katrs drīkst apsēsties vai nu uz tā paša krēsla, vai uz cita krēsla tieši blakus šim krēslam. Cik dažādi skolēnu izvietojumi iespējami pēc pārsēšanās?',
    solution:
      'Ar $a_n$ apzīmējam dažādos iespējamos $n$ skolēnu izvietojumus pēc pārsēšanās. Ievērojam, ka $a_1 = 1$ (skolēns pieceļas un pēc tam atkal apsēžas savā vietā) un $a_2 = 2$ (abi skolēni pieceļas un pēc tam katrs apsēžas savā vietā vai arī abi skolēni apmainās vietām).\n\nApskatām $n$ skolēnus un meklējam formulu, kas izsaka $a_n$. Visas pārsēšanās iedalās divās grupās:\n- Pirmais skolēns paliek uz vietas. Tad pārsēžas tikai atlikušie $(n - 1)$ skolēni un šādu dažādo izvietojumu skaits ir $a_{n-1}$.\n- Pirmais skolēns pāriet uz otro krēslu. Tad uz pirmo krēslu pāriet skolēns no otrā krēsla. Pārējie $(n - 2)$ skolēni pārsēžas „savā starpā" un šādu dažādo izvietojumu skaits ir $a_{n-2}$.\n\nTātad $a_n = a_{n-1} + a_{n-2}$. Izmantojot sākuma nosacījumus un iegūto formulu, iegūstam:\n\n| $n$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|---|---|---|---|---|---|---|---|---|---|---|\n| $a_n$ | 1 | 2 | 3 | 5 | 8 | 13 | 21 | 34 | 55 | 89 |\n\nLīdz ar to iespējami $\\mathbf{89}$ dažādi skolēnu izvietojumi.',
  },
  {
    id: 'ex8',
    problem:
      'Apskatām skaitļus, kas satur tikai ciparus $1; 2; 3$ un kuros cipari $1$ un $3$ neatrodas blakus. Cik ir desmitciparu skaitļu, kas atbilst uzdevuma nosacījumiem?',
    solution:
      'Apskatīsim trīs rekurentas skaitļu virknes. Apzīmējam:\n- $v_n$ — meklēto $n$-ciparu skaitļu skaits, kuru pēdējais cipars ir $1$;\n- $d_n$ — meklēto $n$-ciparu skaitļu skaits, kuru pēdējais cipars ir $2$;\n- $t_n$ — meklēto $n$-ciparu skaitļu skaits, kuru pēdējais cipars ir $3$.\n\nIevērojam, ka:\n- $v_1 = d_1 = t_1 = 1$ (atbilstošie viencipara skaitļi ir $1; 2; 3$);\n- $v_n = v_{n-1} + d_{n-1}$, jo $n$-ciparu skaitļus, kam pēdējais cipars ir $1$, var iegūt no $(n-1)$-ciparu skaitļiem, kam pēdējais cipars ir $1$ vai $2$, tiem beigās pierakstot $1$;\n- $d_n = v_{n-1} + d_{n-1} + t_{n-1}$, jo $n$-ciparu skaitļus, kam pēdējais cipars ir $2$, var iegūt no $(n-1)$-ciparu skaitļiem, kam pēdējais cipars ir $1$, $2$ vai $3$, tiem beigās pierakstot $2$;\n- $t_n = d_{n-1} + t_{n-1}$, jo $n$-ciparu skaitļus, kam pēdējais cipars ir $3$, var iegūt no $(n-1)$-ciparu skaitļiem, kam pēdējais cipars ir $2$ vai $3$, tiem beigās pierakstot $3$.\n\nTātad meklēto $n$-ciparu skaitļu skaits ir $v_n + d_n + t_n = 2(v_{n-1} + d_{n-1} + t_{n-1}) + d_{n-1}$. Tā kā $d_n = v_{n-1} + d_{n-1} + t_{n-1}$, tad $d_{n-1} = v_{n-2} + d_{n-2} + t_{n-2}$. Ja meklēto $n$-ciparu skaitļu skaitu apzīmē ar $a_n$, tad iegūstam $a_n = 2a_{n-1} + a_{n-2}$.\n\nTā kā $a_1 = 3$ (derīgie viencipara skaitļi ir $1; 2; 3$) un $a_2 = 7$ (derīgie divciparu skaitļi ir $11; 12; 21; 22; 23; 32; 33$), tad, izmantojot iegūto formulu, iegūstam:\n\n| $n$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 |\n|---|---|---|---|---|---|---|---|---|---|---|\n| $a_n$ | 3 | 7 | 17 | 41 | 99 | 239 | 577 | 1393 | 3363 | 8119 |\n\nTātad pavisam ir $\\mathbf{8119}$ desmitciparu skaitļi, kas apmierina uzdevuma nosacījumus.',
  },
  {
    id: 'ex9',
    problem:
      'Cik veidos rindā var iestādīt septiņus kokus — liepas, ozolus, priedes un egles — tā, lai nekur blakus neatrastos divi skuju koki? (Nav obligāti jāizmanto visas koku sugas. Veidi, kas atšķiras ar koku secību rindā, ir dažādi.)',
    solution:
      'Ar $k_n$ apzīmējam dažādo veidu skaitu, kā rindā iestādīt $n$ kokus atbilstoši uzdevuma nosacījumiem. Visus šos veidus var sadalīt $2$ grupās atkarībā no pirmā koka:\n- Ja pirmais ir lapu koks ($2$ veidi), tad pārējos $n - 1$ kokus var iestādīt $k_{n-1}$ veidos.\n- Ja pirmais ir skuju koks ($2$ veidi), tad otrajam jābūt lapu kokam ($2$ veidi), bet pārējos $n - 2$ kokus var iestādīt $k_{n-2}$ veidos.\n\nTātad $n$ kokus rindā, atbilstoši uzdevuma nosacījumiem, var iestādīt\n$$k_n = 2 \\cdot k_{n-1} + 2 \\cdot 2 \\cdot k_{n-2} = 2k_{n-1} + 4k_{n-2}$$\nveidos. Tā kā $k_1 = 4$ (liepa, ozols, priede, egle) un $k_2 = 2 \\cdot 4 + 2 \\cdot 2 = 12$ (tas ir, ja pirmais ir lapu koks ($2$ veidi), tad otrais var būt jebkurš no pārējiem četriem kokiem; ja pirmais ir skuju koks ($2$ veidi), tad otrais var būt jebkurš no pārējiem diviem lapu kokiem).\n\nTālāk, izmantojot iegūto formulu $k_n = 2k_{n-1} + 4k_{n-2}$, iegūstam:\n\n| $n$ | 1 | 2 | 3 | 4 | 5 | 6 | 7 |\n|---|---|---|---|---|---|---|---|\n| $k_n$ | 4 | 12 | 40 | 128 | 416 | 1344 | 4352 |\n\nTātad pavisam ir $\\mathbf{4352}$ dažādi veidi, kā rindā iestādīt septiņus kokus, kas apmierina uzdevuma nosacījumus.',
  },
]
